### ISSUE TITLE
Error en el proceso de dump

### ISSUE THREAD

**Issue by ocuil** [cr0hn/enteletaor#1]
Buenas, en primer lugar la charla de la rootedcon increible, la herramienta increible !!! muchas gracias !!!

Realizando estas pruebas:

enteletaor redis discover-dbs -t XXX.XXX.XXX.XXX 
[ \* ] Starting Enteletaor execution
[ \* ] Discovered 'XXX.XXX.XXX DBs at '16':
[ \* ]    - DB0 - 6074 keys
[ \* ]    - DB1 - Empty
[ \* ]    - DB2 - Empty
[ \* ]    - DB3 - Empty
[ \* ]    - DB4 - Empty
[ \* ]    - DB5 - Empty
[ \* ]    - DB6 - Empty
[ \* ]    - DB7 - Empty
[ \* ]    - DB8 - Empty
[ \* ]    - DB9 - Empty
[ \* ]    - DB10 - Empty
[ \* ]    - DB11 - Empty
[ \* ]    - DB12 - Empty
[ \* ]    - DB13 - Empty
[ \* ]    - DB14 - Empty
[ \* ] Done!

enteletaor redis dump -t xxx.xxx.xxx.xxx
# Genera este error:

[ \* ]     ":xxxxxxx9dc9bbdc8a63247410cxxxxxx": "{I"_csrf_token:EFI"xxxxxxxUpiZaAB3bJJLqPnim5z927ETOAbWSDxxxxxxx=;F"
[ \* ]     ":xxxxxxxb0ea7e8a51f440a846xxxxxxx": "{I"_csrf_token:EFI"xxxxxxx4xSn2oaMCQaGMRo3s83bj9GdyL4A5yxxxxxxx=;F"
[ \* ]     "vpsXXXXXX.XXXXXX.net:24691:eab2b25b312a":
[ \* ]     {
[ \* ]      "info":
[ \* ]       {
[ \* ] Unhandled exception: 'str' object has no attribute 'iteritems'

¿Alguna idea?

**Comment by cr0hn** [comment]
podrías ejecutarlo con más nivel de verbosidad?

enteletaor -vvvv redis discover-dbs ....

**Comment by ocuil** [comment]
Claro !!! el problema lo da con el dump, he ejecutado esto:

enteletaor -vvvv redis dump -t XXX.XXX.XXX.XXX

Y el error mas ampliado es:

[ \* ]     "vps1XXXXXX.XXXXXX.net:24691:eab2b25b312a":
[ \* ]     {
[ \* ]      "info":
[ \* ]       {
[ \* ] Unhandled exception: 'str' object has no attribute 'iteritems'
[ \* ] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/enteletaor-1.0.0-py2.7.egg/enteletaor_lib/enteletaor.py", line 25, in main
    run_console(config)
  File "/usr/local/lib/python2.7/dist-packages/enteletaor-1.0.0-py2.7.egg/enteletaor_lib/api.py", line 33, in run_console
    run(config)
  File "/usr/local/lib/python2.7/dist-packages/enteletaor-1.0.0-py2.7.egg/enteletaor_lib/api.py", line 55, in run
    AppSettings.modules[config.action]().run(config)
  File "/usr/local/lib/python2.7/dist-packages/enteletaor-1.0.0-py2.7.egg/enteletaor_lib/modules/**init**.py", line 18, in run
    self.**submodules**[module_config.sub_action]['action'](module_config)
  File "/usr/local/lib/python2.7/dist-packages/enteletaor-1.0.0-py2.7.egg/enteletaor_lib/modules/redis/redis_dump.py", line 175, in action_redis_dump
    decode_object(key, val)
  File "/usr/local/lib/python2.7/dist-packages/enteletaor-1.0.0-py2.7.egg/enteletaor_lib/modules/redis/redis_dump.py", line 47, in decode_object
    _decode_object(val, ident)
  File "/usr/local/lib/python2.7/dist-packages/enteletaor-1.0.0-py2.7.egg/enteletaor_lib/modules/redis/redis_dump.py", line 92, in _decode_object
    _decode_object(v, _new_ident + 2)
  File "/usr/local/lib/python2.7/dist-packages/enteletaor-1.0.0-py2.7.egg/enteletaor_lib/modules/redis/redis_dump.py", line 60, in _decode_object
    for k, v in six.iteritems(val):
  File "/usr/lib/python2.7/dist-packages/six.py", line 565, in iteritems
    return iter(d.iteritems(**kw))
AttributeError: 'str' object has no attribute 'iteritems'

#Muchas grcias de antemano =)

**Comment by cr0hn** [comment]
Okis, gracias. Lo miro lo reviso para la siguiente revision.
